project:
  type: website
  output-dir: docs
website:
  title: "Yoselyn_Ramirez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about_me.qmd
        text: About_me
      - href: posts/Blog.qmd
        text: Blogs

format:
  html:
    theme: lux
    css: styles.css
    toc: True
    page-layout: full

editor: visual

