project:
  type: website
  output-dir: docs
website:
  title: "Yoselyn_Ramirez.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: false
    page-layout: full

editor: visual

