<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Yoselyn_Ramirez - My Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Yoselyn_Ramirez</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about_me.html"> 
<span class="menu-text">About_me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../posts/Blog.html"> 
<span class="menu-text">Blogs</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-left">
      <h1 class="title">My Analysis</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta column-page-left">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#perimeter-true-color-image-false-color-image-map-air-quality" id="toc-perimeter-true-color-image-false-color-image-map-air-quality" class="nav-link active" data-scroll-target="#perimeter-true-color-image-false-color-image-map-air-quality">Perimeter, True color image, False color image, Map &amp; Air Quality</a>
  <ul class="collapse">
  <li><a href="#the-following-code-will-use-data-from-the-sources-below" id="toc-the-following-code-will-use-data-from-the-sources-below" class="nav-link" data-scroll-target="#the-following-code-will-use-data-from-the-sources-below">The following code will use data from the sources below</a></li>
  </ul></li>
  <li><a href="#before-we-begin-a-little-on-the-thomas-fire-perimeter" id="toc-before-we-begin-a-little-on-the-thomas-fire-perimeter" class="nav-link" data-scroll-target="#before-we-begin-a-little-on-the-thomas-fire-perimeter">Before we begin, a little on the Thomas fire perimeter</a></li>
  <li><a href="#satellite-imagery-that-we-will-explore" id="toc-satellite-imagery-that-we-will-explore" class="nav-link" data-scroll-target="#satellite-imagery-that-we-will-explore">Satellite Imagery that we will explore</a></li>
  <li><a href="#true-color-image-rgb" id="toc-true-color-image-rgb" class="nav-link" data-scroll-target="#true-color-image-rgb">True color image (RGB)</a>
  <ul class="collapse">
  <li><a href="#bands-summary" id="toc-bands-summary" class="nav-link" data-scroll-target="#bands-summary">Bands summary</a></li>
  </ul></li>
  <li><a href="#lets-look-at-rgb-output" id="toc-lets-look-at-rgb-output" class="nav-link" data-scroll-target="#lets-look-at-rgb-output">Let’s look at RGB output</a>
  <ul class="collapse">
  <li><a href="#importance-of-true-color-images-for-analyzing-data" id="toc-importance-of-true-color-images-for-analyzing-data" class="nav-link" data-scroll-target="#importance-of-true-color-images-for-analyzing-data">Importance of True Color Images for Analyzing Data:</a></li>
  <li><a href="#summarylimitations-of-true-color-images" id="toc-summarylimitations-of-true-color-images" class="nav-link" data-scroll-target="#summarylimitations-of-true-color-images">Summary/Limitations of True Color Images:</a></li>
  </ul></li>
  <li><a href="#false-color-image" id="toc-false-color-image" class="nav-link" data-scroll-target="#false-color-image">False color image</a>
  <ul class="collapse">
  <li><a href="#bands-summary-1" id="toc-bands-summary-1" class="nav-link" data-scroll-target="#bands-summary-1">Bands Summary</a></li>
  <li><a href="#why-false-color-imaging-is-important" id="toc-why-false-color-imaging-is-important" class="nav-link" data-scroll-target="#why-false-color-imaging-is-important">Why false color imaging is important</a></li>
  </ul></li>
  <li><a href="#time-to-map-the-thomas-fire" id="toc-time-to-map-the-thomas-fire" class="nav-link" data-scroll-target="#time-to-map-the-thomas-fire">Time to Map the Thomas Fire</a>
  <ul class="collapse">
  <li><a href="#thomas-fire-outlined-in-red-with-false-color-image" id="toc-thomas-fire-outlined-in-red-with-false-color-image" class="nav-link" data-scroll-target="#thomas-fire-outlined-in-red-with-false-color-image">Thomas Fire outlined in red with False Color Image</a></li>
  </ul></li>
  <li><a href="#next-we-will-look-at-the-air-quality-index-during-the-time-of-the-thomas-fire." id="toc-next-we-will-look-at-the-air-quality-index-during-the-time-of-the-thomas-fire." class="nav-link" data-scroll-target="#next-we-will-look-at-the-air-quality-index-during-the-time-of-the-thomas-fire.">Next we will look at the Air Quality Index during the time of the Thomas Fire.</a></li>
  <li><a href="#plot-the-aqi-highlighting-the-thomas-fire-dates" id="toc-plot-the-aqi-highlighting-the-thomas-fire-dates" class="nav-link" data-scroll-target="#plot-the-aqi-highlighting-the-thomas-fire-dates">Plot the AQI highlighting the Thomas Fire dates</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block column-page-left" id="quarto-document-content">





<p>Author: Yos Ramirez</p>
<center>
<strong>Thomas Fire</strong>
</center>
<section id="perimeter-true-color-image-false-color-image-map-air-quality" class="level2">
<h2 class="anchored" data-anchor-id="perimeter-true-color-image-false-color-image-map-air-quality">Perimeter, True color image, False color image, Map &amp; Air Quality</h2>
<p>This code is designed to provide visual context for analyzing wildfire impacts using satellite imagery, combined with air quality data to assess the environmental and health consequences. Specifically this code will look at the Thomas Fire taht occurred in 2017.</p>
<section id="the-following-code-will-use-data-from-the-sources-below" class="level3">
<h3 class="anchored" data-anchor-id="the-following-code-will-use-data-from-the-sources-below">The following code will use data from the sources below</h3>
<p>The first dataset contains information a <a href="https://planetarycomputer.microsoft.com/dataset/landsat-c2-l2">simplified collection of bands (red, green, blue, near-infrared and shortwave infrared)</a>.</p>
<p>Microsoft. (n.d.). Landsat Collection 2 Level-2 (C2 L2) data [Data set]. Microsoft Planetary Computer. Retrieved November 23, 2024, from https://planetarycomputer.microsoft.com/dataset/landsat-c2-l2</p>
<p>The second dataset is <a href="https://catalog.data.gov/dataset/california-fire-perimeters-all-b3436">historical open-access data about fire perimeters in California</a> from Data.gov.</p>
<p>U.S. Government. (n.d.). California fire perimeters (ALL) [Data set]. Data.gov. Retrieved November 23, 2024, from https://catalog.data.gov/dataset/california-fire-perimeters-all-b3436</p>
<p><a href="https://www.airnow.gov/aqi/aqi-basics/">Air Quality Index (AQI)</a> data from the <a href="https://www.epa.gov">US Environmental Protection Agency</a> to visualize the impact on the AQI of the 2017 <a href="https://en.wikipedia.org/wiki/Thomas_Fire">Thomas Fire</a> in Santa Barbara County.</p>
</section>
</section>
<section id="before-we-begin-a-little-on-the-thomas-fire-perimeter" class="level2">
<h2 class="anchored" data-anchor-id="before-we-begin-a-little-on-the-thomas-fire-perimeter">Before we begin, a little on the Thomas fire perimeter</h2>
<p>To analyze the Thomas we first need to get the parameters in a shapefile. In a previous .ipynb code chunk I manually selected for the parameter of the Thomas Fire. To briefly explain that code that is not in this blog:</p>
<ul>
<li><p>I imported essential libraries like requests, zipfile, geopandas, and shutil to download, extract, and manipulate geospatial data</p></li>
<li><p>I downloaded a ZIP file containing fire perimeter shapefiles from the public URL provided and extract the contents into a temporary directory</p></li>
<li><p>I loaded the shapefile into a GeoDataFrame and checked the CRS, which I identified as a projected CRS in meters</p></li>
<li><p>I listed the unique fire names and focused on retrieving the Thomas Fire (2017) by filtering based on the FIRE_NAME and YEAR_ columns</p></li>
<li><p>I filtered the dataset to select for the Thomas Fire boundary in 2017, specifically where FIRE_NAME is “THOMAS” and YEAR_ is 2017</p></li>
<li><p>I saved the selected perimeter data for the Thomas Fire as a shapefile in a data directory folder, and finally I deleted the temporary extraction directory to keep the workspace clean.</p></li>
<li><p>The Thomas Fire shapefile is the file I use for this code and is saved as ‘Thomas_fire_perimeter.shp’.</p></li>
</ul>
</section>
<section id="satellite-imagery-that-we-will-explore" class="level2">
<h2 class="anchored" data-anchor-id="satellite-imagery-that-we-will-explore">Satellite Imagery that we will explore</h2>
<ul>
<li><p>True color image (RGB)</p></li>
<li><p>False color image</p></li>
</ul>
</section>
<section id="true-color-image-rgb" class="level2">
<h2 class="anchored" data-anchor-id="true-color-image-rgb">True color image (RGB)</h2>
<p>What is a True Color Image (Red Green Blue)?</p>
<p>A True Color Image is as it sounds, a visual representation of satellite data where the colors correspond to the red, green, and blue components of the light spectrum, the primary colors of light that the human eye can perceive. When combined, they form a full spectrum of visible colors, with the same idea in mind this is applied to remote sensing and geospatial analysis. Combining data from three specific bands of a satellite image or raster data, creates a true color image. The three bands as you can guess are red, green, and blue, and are very important to plotting the satellite data as you will see in the next few code chunks.</p>
<section id="bands-summary" class="level3">
<h3 class="anchored" data-anchor-id="bands-summary">Bands summary</h3>
<p>- Red Band (corresponds to the red light wavelength, similar to the human eye)</p>
<p>- Green Band (corresponds to the green light wavelength, similar to the human eye))</p>
<p>- Blue Band (corresponds to the blue light wavelength, similar to the human eye))</p>
<section id="import-libraries" class="level4">
<h4 class="anchored" data-anchor-id="import-libraries">Import libraries</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>python:         /Users/yos/opt/anaconda3/bin/python3
libpython:      /Users/yos/opt/anaconda3/lib/libpython3.8.dylib
pythonhome:     /Users/yos/opt/anaconda3:/Users/yos/opt/anaconda3
version:        3.8.8 (default, Apr 13 2021, 12:59:45)  [Clang 10.0.0 ]
numpy:          /Users/yos/opt/anaconda3/lib/python3.8/site-packages/numpy
numpy_version:  1.24.4

NOTE: Python version was forced by use_python() function</code></pre>
</div>
</div>
<div class="cell" data-tags="[]">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> rioxarray <span class="im">as</span> rioxr</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> fiona</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> rasterio</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> rasterio.plot <span class="im">import</span> show</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-in-data" class="level4">
<h4 class="anchored" data-anchor-id="load-in-data">Load in data</h4>
<div class="cell" data-tags="[]">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Construct the file path</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>base_dir <span class="op">=</span> <span class="st">'data'</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>landsat <span class="op">=</span> <span class="st">'landsat8-2018-01-26-sb-simplified.nc'</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>file_path <span class="op">=</span> os.path.join(base_dir, landsat)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Open the raster data</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>landsat_data <span class="op">=</span> rioxr.open_rasterio(file_path)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Print landsat data</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(landsat_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;xarray.Dataset&gt;
Dimensions:      (band: 1, x: 870, y: 731)
Coordinates:
  * band         (band) int64 1
  * x            (x) float64 1.213e+05 1.216e+05 ... 3.557e+05 3.559e+05
  * y            (y) float64 3.952e+06 3.952e+06 ... 3.756e+06 3.755e+06
    spatial_ref  int64 0
Data variables:
    red          (band, y, x) float64 ...
    green        (band, y, x) float64 ...
    blue         (band, y, x) float64 ...
    nir08        (band, y, x) float64 ...
    swir22       (band, y, x) float64 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print CRS</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Current CRS:"</span>, landsat_data.rio.crs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Current CRS: EPSG:32611</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>landsat_data <span class="op">=</span> landsat_data.rio.reproject(<span class="st">"EPSG:3857"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Update CRS</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Updated CRS:"</span>, landsat_data.rio.crs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Updated CRS: EPSG:3857</code></pre>
</div>
</div>
</section>
<section id="explore-some-key-information-on-the-data" class="level4">
<h4 class="anchored" data-anchor-id="explore-some-key-information-on-the-data">Explore some key information on the data</h4>
<div class="cell" data-tags="[]">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print coordinates</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Dataset Coordinates:"</span>,landsat_data.coords)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Dataset Coordinates: Coordinates:
  * x            (x) float64 -1.349e+07 -1.349e+07 ... -1.32e+07 -1.32e+07
  * y            (y) float64 4.26e+06 4.26e+06 4.259e+06 ... 4.012e+06 4.012e+06
  * band         (band) int64 1
    spatial_ref  int64 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print dimensions</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Dataset Dimensions:"</span>,landsat_data.dims)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Dataset Dimensions: Frozen({'x': 889, 'y': 757, 'band': 1})</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print band names and values</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Band Names and Values:"</span>,landsat_data.data_vars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Band Names and Values: Data variables:
    red      (band, y, x) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    green    (band, y, x) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    blue     (band, y, x) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    nir08    (band, y, x) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    swir22   (band, y, x) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0</code></pre>
</div>
</div>
<p>After exploration of the data, that is important in determining the next steps to take for the final output of a RGB image, I was able to obtain the following. The data is geospatial data with x, y, which represent the spatial grid and band. The band variables are red, green, blue which we need for a true color image alomng with nir08, and swir22 which we will need in the next part. Each variable has 5mb of data and are float64 or a number that can be a decimal. The dimensions are 889 for the x longitude, and 757 for the y latitude. The crs is WGS 84 or pseudo mercator. The scale factor is 1.0 not requiring alteration.</p>
<div class="cell" data-tags="[]">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop single band with squeeze </span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>landsat_data <span class="op">=</span> landsat_data.squeeze()</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop variables associated with band</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>landsat_data <span class="op">=</span> landsat_data.drop_vars(<span class="st">'band'</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Verify dimensions and coordinates</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(landsat_data.dims, landsat_data.coords)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Frozen({'x': 889, 'y': 757}) Coordinates:
  * x            (x) float64 -1.349e+07 -1.349e+07 ... -1.32e+07 -1.32e+07
  * y            (y) float64 4.26e+06 4.26e+06 4.259e+06 ... 4.012e+06 4.012e+06
    spatial_ref  int64 0</code></pre>
</div>
</div>
<ul>
<li><p>The squeeze() method is used to remove dimensions of size 1 from an array. This is important when the dataset has dimensions that are not necessary, which could result in confusion or the need for extra processing.</p></li>
<li><p>The drop_vars() method is used to drop specific variables from a dataset. For this geospatial data it is removing metadata variables, associated with the band previously dropped, that are no longer required.</p></li>
</ul>
</section>
</section>
</section>
<section id="lets-look-at-rgb-output" class="level2">
<h2 class="anchored" data-anchor-id="lets-look-at-rgb-output">Let’s look at RGB output</h2>
<p>Ensuring the use of <code>robust=True</code></p>
<p>This operation fixes the geometries that may be causing a failure that skew the RGB data, resulting in a fixed true-color image.</p>
<p>The issue here is the clouds, their RGB values are outliers and cause the other values to be squished when plotting.</p>
<div class="cell" data-tags="[]">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot landsat data as rbg array, include robust true to fix outliers</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>landsat_data[[<span class="st">'red'</span>, <span class="st">'green'</span>, <span class="st">'blue'</span>]].to_array().plot.imshow(robust<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'RGB Image (True Color)'</span>) </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="False-color-blog-Ramirez_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="importance-of-true-color-images-for-analyzing-data" class="level3">
<h3 class="anchored" data-anchor-id="importance-of-true-color-images-for-analyzing-data">Importance of True Color Images for Analyzing Data:</h3>
<p>True color images provide a realistic view of the Earth’s surface, a natural representation, similar to what we would see with our own eyes. This can be useful for quickly understanding the landscape, vegetation, water bodies, urban areas, and other natural features. Often true color image is necessary in determining the next spatial analysis to make. As for this analysis of the Thomas Fire, the areas affected by the fire need to be better visualized and so another type of satellite imagery is explored next.</p>
</section>
<section id="summarylimitations-of-true-color-images" class="level3">
<h3 class="anchored" data-anchor-id="summarylimitations-of-true-color-images">Summary/Limitations of True Color Images:</h3>
<ul>
<li><p><strong>Easy visual interpretation</strong> - land cover, as it looks similar to the naked eye.</p></li>
<li><p><strong>Cannot See Non-visible Wavelengths</strong> - like infrared, which can be useful for vegetation health analysis.</p></li>
<li><p><strong>Cloud Cover</strong> - special processing is needed, such are <code>robust=True</code>.</p></li>
</ul>
</section>
</section>
<section id="false-color-image" class="level2">
<h2 class="anchored" data-anchor-id="false-color-image">False color image</h2>
<p>Why is it False?</p>
<p>A false color image is a type of image in which other electromagnetic spectrum colors are used to represent different features or properties of the landscape. The colors do not correspond to the colors normally seen with the naked eye. Similar to true color image, false color image needs infrared, short wave infrared, and near infrared bands to highlight specific features.</p>
<section id="bands-summary-1" class="level3">
<h3 class="anchored" data-anchor-id="bands-summary-1">Bands Summary</h3>
<ul>
<li>Infrared (IR),</li>
<li>short-wave infrared (SWIR)</li>
<li>near-infrared (NIR)</li>
</ul>
</section>
<section id="why-false-color-imaging-is-important" class="level3">
<h3 class="anchored" data-anchor-id="why-false-color-imaging-is-important">Why false color imaging is important</h3>
<ul>
<li><strong>Vegetation Analysis - as we will explore with the Thomas Fire</strong></li>
</ul>
<section id="example-of-a-false-color-image" class="level4">
<h4 class="anchored" data-anchor-id="example-of-a-false-color-image">Example of a false color image</h4>
<div class="cell" data-tags="[]">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot landsat data as false color image as array, include robust true to fix outliers</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>landsat_data[[<span class="st">'swir22'</span>, <span class="st">'nir08'</span>, <span class="st">'red'</span>]].to_array().plot.imshow(robust<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"False Color Image"</span>) <span class="co"># Title of plot</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>plt.show() <span class="co"># Show plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="False-color-blog-Ramirez_files/figure-html/unnamed-chunk-8-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="time-to-map-the-thomas-fire" class="level2">
<h2 class="anchored" data-anchor-id="time-to-map-the-thomas-fire">Time to Map the Thomas Fire</h2>
<section id="read-in-data-for-the-perimeter" class="level4">
<h4 class="anchored" data-anchor-id="read-in-data-for-the-perimeter">Read in data for the perimeter</h4>
<div class="cell" data-tags="[]">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import thomas shape file</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>fire_shapefile <span class="op">=</span> <span class="st">'data/Thomas_fire_perimeter.shp'</span> <span class="co"># File path</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>thomas_fire <span class="op">=</span> gpd.read_file(fire_shapefile) <span class="co"># Read in file with file path</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="make-sure-crs-is-the-same" class="level4">
<h4 class="anchored" data-anchor-id="make-sure-crs-is-the-same">Make sure CRS is the same</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make crs the same for both data</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>thomas_fire <span class="op">=</span> thomas_fire.to_crs(landsat_data.rio.crs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="thomas-fire-outlined-in-red-with-false-color-image" class="level3">
<h3 class="anchored" data-anchor-id="thomas-fire-outlined-in-red-with-false-color-image">Thomas Fire outlined in red with False Color Image</h3>
<div class="cell" data-tags="[]">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot Thomas fire parimeter with false color imagery</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">10</span>)) <span class="co"># Figure size</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>landsat_data[[<span class="st">'swir22'</span>,<span class="st">'nir08'</span>,<span class="st">'red'</span>]].to_array().plot.imshow(robust<span class="op">=</span><span class="va">True</span>, <span class="co"># Plot false color from landsat data as array</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>                                                              ax<span class="op">=</span>ax) <span class="co"># Set axis</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>thomas_fire.boundary.plot(ax<span class="op">=</span>ax, <span class="co"># Set axis</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>                          edgecolor<span class="op">=</span><span class="st">'red'</span>, <span class="co"># Boundary color</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>                          linewidth<span class="op">=</span><span class="dv">2</span>, <span class="co"># Boundary width</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>                          label<span class="op">=</span><span class="st">"Thomas Fire Perimeter"</span>) <span class="co"># Boundary label</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Thomas Fire with False Color Imagery"</span>) <span class="co"># Title of plot</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>plt.legend() <span class="co"># Legend</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>plt.show() <span class="co"># Show plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="False-color-blog-Ramirez_files/figure-html/unnamed-chunk-11-5.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<section id="figure-description" class="level4">
<h4 class="anchored" data-anchor-id="figure-description">Figure description</h4>
<p>The figure above shows the area of Santa Barbara county which the Thomas fire occurred in 2017, with a red outline for clarity. The image is in short-wave infrared, near-infrared, and red considered to better visualize where the fire occurred. This technique allows for better identification of burned areas. The false color image clearly shows the red land compared to the green, as the NIR band highlights vegetation and areas affected by fire, while the SWIR band distinguishes between different land cover types. Darker red means the area has been burned recently, the lighter red shown above means the area has been burned but not so recent, in 2017.</p>
</section>
</section>
</section>
<section id="next-we-will-look-at-the-air-quality-index-during-the-time-of-the-thomas-fire." class="level2">
<h2 class="anchored" data-anchor-id="next-we-will-look-at-the-air-quality-index-during-the-time-of-the-thomas-fire.">Next we will look at the Air Quality Index during the time of the Thomas Fire.</h2>
<p>Air quality during and after fires is critically important for several reasons, as wildfires and even smaller fires can release a variety of harmful pollutants into the air, which pose serious health risks to humans and animals. During a wildfire, a number of harmful substances are released into the air. These pollutants can have immediate and long-term health impacts, particularly for vulnerable populations such as children, the elderly, and people with pre-existing health conditions. Wildfires can have a devastating impact on local ecosystems, and poor air quality during and after fires can harm vegetation and animal life.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>aqi_17 <span class="op">=</span> pd.read_csv(<span class="st">"data/daily_aqi_by_county_2017.csv"</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>aqi_18 <span class="op">=</span> pd.read_csv(<span class="st">"data/daily_aqi_by_county_2018.csv"</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine datasets (2017 and 2018)</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>aqi <span class="op">=</span> pd.concat([aqi_17, aqi_18])</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Simplify column names</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>aqi.columns <span class="op">=</span> (aqi.columns</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>                  .<span class="bu">str</span>.lower()</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>                  .<span class="bu">str</span>.replace(<span class="st">' '</span>, <span class="st">'_'</span>)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>                )</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Save filtered (Santa Barbara) data </span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>aqi_sb <span class="op">=</span> aqi[aqi[<span class="st">'county_name'</span>] <span class="op">==</span> <span class="st">'Santa Barbara'</span>]</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only specific columns (date, aqi, category, defining_parameter, defining_site, and number_of_sites_reporting)</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>aqi_sb <span class="op">=</span> aqi_sb[[<span class="st">'date'</span>, <span class="st">'aqi'</span>, <span class="st">'category'</span>, <span class="st">'defining_parameter'</span>, <span class="st">'defining_site'</span>, <span class="st">'number_of_sites_reporting'</span>]]</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert specific object column (date) to datetime object</span></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>aqi_sb[<span class="st">'date'</span>] <span class="op">=</span> pd.to_datetime(aqi_sb[<span class="st">'date'</span>])</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Save with new (date) index</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>aqi_sb <span class="op">=</span> aqi_sb.set_index(<span class="st">'date'</span>).sort_index()</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Add new 5 day mean column to data (Santa Barbara)</span></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>aqi_sb[<span class="st">'five_day_average'</span>] <span class="op">=</span> aqi_sb[<span class="st">'aqi'</span>].rolling(window<span class="op">=</span><span class="st">'5D'</span>).mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plot-the-aqi-highlighting-the-thomas-fire-dates" class="level2">
<h2 class="anchored" data-anchor-id="plot-the-aqi-highlighting-the-thomas-fire-dates">Plot the AQI highlighting the Thomas Fire dates</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot figure</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">7</span>))</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot aqi , label, color, size, and transparency</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>plt.plot(aqi_sb.index.values, aqi_sb[<span class="st">'aqi'</span>].values, label<span class="op">=</span><span class="st">'Daily AQI'</span>, color<span class="op">=</span><span class="st">'darkblue'</span>, linewidth<span class="op">=</span><span class="dv">1</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot average, label, color, and size</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>plt.plot(aqi_sb.index.values, aqi_sb[<span class="st">'five_day_average'</span>].values, label<span class="op">=</span><span class="st">'5-Day Average AQI'</span>, color<span class="op">=</span><span class="st">'fuchsia'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Title and size</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Daily AQI and 5-Day Average AQI (Santa Barbara County)'</span>, fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="co"># X label and size</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Date'</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Y label and size</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'AQI'</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Rotate x-axis labels</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(array([17167., 17257., 17348., 17440., 17532., 17622., 17713., 17805.,
       17897.]), [Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, '')])</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Legend</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Grid</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>plt.grid() </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Add shaded area for Thomas fire</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>plt.axvspan(pd.Timestamp(<span class="st">'2017-12-01'</span>), pd.Timestamp(<span class="st">'2017-12-31'</span>), color<span class="op">=</span><span class="st">'yellow'</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Layout</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Show plot</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="False-color-blog-Ramirez_files/figure-html/unnamed-chunk-13-7.png" class="img-fluid figure-img" width="1344"></p>
</figure>
</div>
</div>
</div>
<p>The air quality during the Thomas Fire was high. The Thomas fire shows a spike in the aqi daily shown in blue and 5 day average shown in pink. I’ve highlighted the month of December yellow to clarify the spike occurence. I suggest doing this to clearly identify the time of interest. It is clear that the daily aqi was much higher than the 5 day average but the 5 day average does remain high for a while compared to normal days. The daily aqi dropped from the highest point to where the average remained. For atleast half of the month of December the daily aqi and the 5 day average were above 150 in which pollution would be a problem. This data visualization shows the importance of being able to gather data and applying the skills of analysis.</p>
<p>Data analysis helps identify the sources and patterns of pollution, whether it’s from industrial activities, vehicle emissions, agricultural runoff, or natural events like wildfires. Understanding where and when pollutants are released is the first step in controlling them. By analyzing historical data, we can detect trends in pollution levels, such as increases or decreases in air, water, or soil quality over time. This can help policymakers and environmental agencies make informed decisions about interventions. Data analysis allows for the creation of clear, visual representations of pollution levels, such as maps, graphs, and interactive dashboards. Data analysis can identify areas where pollution control technologies can be most effective, encouraging innovation in clean energy, waste management, or pollution-reducing technologies.</p>
<p>Some information on a few useful libraries</p>
<ol type="1">
<li><p>When working with datasets or results that are stored in different directories, <code>os</code> helps you manage file paths, allowing your code to be flexible and system-agnostic. For example, os.path.join() is used to create platform-independent file paths.</p></li>
<li><p>As for <code>rioxarray</code>, this is an extension of the xarray library for handling geospatial raster data (like satellite imagery or other geospatial data formats). It leverages rasterio to read, write, and process raster files.</p></li>
<li><p>For visualizations <code>matplotlib.pyplot</code> is one of the most commonly used libraries in Python for creating static, interactive, and animated plots and graphs as seen in this blog. In geospatial analysis, you can use plt.imshow() to visualize raster images (such as satellite imagery) and adjust color maps to highlight different features (e.g., vegetation or urban areas).</p></li>
<li><p>Geospatial data, rasters and vectors, often require heavy manipulation and <code>numpy</code> enables efficient handling of large datasets. As well as performing manipulations on multi-dimensional arrays, which can be common in remote sensing.</p></li>
</ol>
<center>
<strong>That’s it for the Thomas Fire Blog</strong>
</center>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>